include("${CMAKE_CURRENT_LIST_DIR}/biosignalmlTargets.cmake")

GET_FILENAME_COMPONENT (SELF_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${SELF_DIR}" PATH)
if (NOT WIN32)
  GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
  GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
endif (NOT WIN32)

set(biosignalml_INCLUDE_DIR "${_IMPORT_PREFIX}/include/biosignalml")
set(biosignalml_LIBRARY_DIR "${_IMPORT_PREFIX}/lib")

